ENT.Base 			= "npc_vj_creature_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Erectus"
ENT.Author 			= "An average Beanmann"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "big b0ne(r)."
ENT.Instructions 	= "rattle me bones"
ENT.Category		= "Bean's Half-Life Coop Infected Expansions"