ENT.Base 			= "npc_vj_creature_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Thrall"
ENT.Author 			= "An average Beanmann"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "I know not what I do."
ENT.Instructions 	= "Chaos Reigns!"
ENT.Category		= "Bean's Half-Life Coop Infected Expansions"